name: Create Pull Request to Main

on:
  push:
    branches-ignore:
      - main

jobs:
  create_pull_request:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Create Pull Request
        run: |
          # Determine the current branch name
          CURRENT_BRANCH=$(git branch --show-current)
          
          # Create a pull request to the 'main' branch
          git checkout -b feature-branch
          git push origin feature-branch
          hub pull-request -b main -h feature-branch -m "Automated pull request from $CURRENT_BRANCH"

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
